language: python

# sudo: false

compiler:
  - gcc

python: "3.4"

services:
  - memcached
  - postgresql

addons:
  postgresql: 9.3

env:
  matrix:
    - DB=postgres
  global:
    - PIP_DOWNLOAD_CACHE=".pip_download_cache"

before_install:
    # Setup a wildcard local DNS for *.local, add proper c++-compiler for node-sass
    - sudo apt-get update
    - sudo apt-get install -qq -y --force-yes dnsmasq
    - echo "listen-address=127.0.0.1" | sudo tee -a /etc/dnsmasq.conf > /dev/null
    - echo "bind-interfaces" | sudo tee -a /etc/dnsmasq.conf > /dev/null
    - echo "address=/local/127.0.0.1" | sudo tee -a /etc/dnsmasq.conf > /dev/null
    - echo "user=root" | sudo tee -a /etc/dnsmasq.conf > /dev/null
    - sudo service dnsmasq restart
    - npm config set python /usr/bin/python2.7
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get install gcc-4.8 g++-4.8
    - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 20
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 20
    - sudo g++ --version

before_script:
  - psql -c 'create database keybar_test;' -U postgres

script:
  - psql --version
  - make develop
  - make test

after_success:
  - pip install "coveralls==0.4.1" coverage
  - coverage report
  - coveralls
