language: python

# sudo: false

compiler:
  - gcc

python: "3.4"

services:
  - memcached
  - redis-server

env:
  matrix:
    - DB=postgres
  global:
    - PIP_DOWNLOAD_CACHE=".pip_download_cache"

before_install:
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update
    - sudo apt-get purge -q postgresql-9.3 postgresql-9.2 postgresql-9.1-postgis-scripts postgresql-9.2-postgis-scripts postgresql-9.3-postgis-scripts postgresql-client postgresql-client-9.2  postgresql-client-9.3 liblwgeom-2.1.3 postgis
    - sudo apt-get autoremove -q --purge
    - sudo apt-get install -qq postgresql-9.4 postgresql-server-dev-9.4
    # Setup a wildcard local DNS for *.local, add proper c++- compiler for node-sass
    - sudo apt-get update
    - sudo apt-get install -qq -y --force-yes dnsmasq
    - sudo apt-get install gcc-4.8 g++-4.8
    - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 20
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 20
    - sudo g++ --version
    - echo "listen-address=127.0.0.1" | sudo tee -a /etc/dnsmasq.conf > /dev/null
    - echo "bind-interfaces" | sudo tee -a /etc/dnsmasq.conf > /dev/null
    - echo "address=/local/127.0.0.1" | sudo tee -a /etc/dnsmasq.conf > /dev/null
    - echo "user=root" | sudo tee -a /etc/dnsmasq.conf > /dev/null
    - sudo service dnsmasq restart
    - sudo service postgresql start 9.4
    - npm config set python /usr/bin/python2.7

before_script:
  - psql -c 'create database keybar_test;' -U postgres

script:
  - psql --version
  - make develop
  - make test

after_success:
  - pip install "coveralls==0.4.1" coverage
  - coverage report
  - coveralls
