language: python
python: "3.4"

addons:
  postgresql: '9.4'

services:
  - memcached
  - redis-server

compiler:
  - gcc

cache:
  directories:
    - node_modules
    - $HOME/.cache/pip/
    - bower_components
    - $HOME/virtualenv/python3.4.2

env:
  global:
    - DJANGO_SETTINGS_MODULE="keybar.conf.travis"
    - KEYBAR_TEST_DB_NAME=keybar_test
    - KEYBAR_TEST_DB_USER=travis

before_install:
  # Reference custom repos
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

  # add proper c++- compiler for node-sass
  - sudo apt-get install gcc-4.7 g++-4.8
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 20
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 20
  - sudo g++ --version
  - npm config set python /usr/bin/python2.7

  # Setup a wildcard local DNS for *.local
  - sudo apt-get install -qq -y --force-yes dnsmasq
  - echo "listen-address=127.0.0.1" | sudo tee -a /etc/dnsmasq.conf > /dev/null
  - echo "bind-interfaces" | sudo tee -a /etc/dnsmasq.conf > /dev/null
  - echo "address=/local/127.0.0.1" | sudo tee -a /etc/dnsmasq.conf > /dev/null
  - echo "user=root" | sudo tee -a /etc/dnsmasq.conf > /dev/null
  - sudo service dnsmasq restart

before_script:
  - psql -c 'create database keybar_test;' -U postgres

script:
  - psql --version
  - make develop
  - make test

after_success:
  - pip install "coveralls==0.4.1" coverage
  - coverage report
  - coveralls
