language: python
python: '3.4'
sudo: false

addons:
  postgresql: '9.4'
  hosts:
    - keybar.local
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - debian-sid
    packages:
      - gcc-4.7
      - g++-4.8
      - openssl/debian-sid
      - libssl-dev/debian-sid

services:
  - memcached
  - redis-server

compiler:
  - gcc

cache:
  apt: true
  directories:
    - node_modules
    - $HOME/.cache/pip/
    - bower_components
    - $HOME/virtualenv/python3.4.2

env:
  global:
    - DJANGO_SETTINGS_MODULE="keybar.conf.travis"
    - KEYBAR_TEST_DB_NAME=keybar_test
    - KEYBAR_TEST_DB_USER=travis

before_install:
  - g++ --version
  - npm config set python /usr/bin/python2.7

before_script:
  - psql -c 'create database keybar_test;' -U postgres

script:
  - openssl version
  - openssl ciphers -v 'TLSv1.2' | head -4
  - psql --version
  - make develop
  - make test
