language: python

sudo: false

python: "3.4"

services:
  - memcached
  - postgresql

addons:
  postgresql: 9.3

env:
  matrix:
    - DB=postgres
  global:
    - PIP_DOWNLOAD_CACHE=".pip_download_cache"

before_install:
    # Setup a wildcard local DNS for *.local
    - sudo apt-get install -qq -y --force-yes dnsmasq
    - echo "listen-address=127.0.0.1" | sudo tee -a /etc/dnsmasq.conf > /dev/null
    - echo "bind-interfaces" | sudo tee -a /etc/dnsmasq.conf > /dev/null
    - echo "address=/local/127.0.0.1" | sudo tee -a /etc/dnsmasq.conf > /dev/null
    - echo "user=root" | sudo tee -a /etc/dnsmasq.conf > /dev/null
    - sudo service dnsmasq restart

before_script:
  - psql -c 'create database keybar_test;' -U postgres

script:
  - psql --version
  - make develop
  - make test

after_success:
  - pip install "coveralls==0.4.1" coverage
  - coverage report
  - coveralls
