language: python

# sudo: false

compiler:
  - gcc

python: "3.4"

services:
  - memcached
  - redis-server

env:
  matrix:
    - DB=postgres
  global:
    - PIP_DOWNLOAD_CACHE=".pip_download_cache"

before_install:
  - sudo apt-get update -qq

  # Remove the default PostgreSQL
  - sudo apt-get remove postgis libpq5 libpq-dev postgresql-9.1-postgis postgresql-9.2-postgis postgresql-9.3-postgis postgresql-9.1 postgresql-9.2 postgresql-9.3
  - sudo apt-get remove libgdal1
  - sudo apt-get autoremove -q --purge

  # Reference custom repos
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

  # Install custom PostgreSQL 9.4
  - sudo apt-get install postgresql-9.4 postgresql-client-9.4 postgresql-server-dev-9.4
  - sudo wget https://raw.githubusercontent.com/travis-ci/travis-cookbooks/master/ci_environment/postgresql/templates/ubuntu/pg_hba.conf.erb
  - sudo mv pg_hba.conf.erb /etc/postgresql/9.4/main/pg_hba.conf
  - sudo service postgresql restart 9.4

  # Setup a wildcard local DNS for *.local
  - sudo apt-get install -qq -y --force-yes dnsmasq
  - echo "listen-address=127.0.0.1" | sudo tee -a /etc/dnsmasq.conf > /dev/null
  - echo "bind-interfaces" | sudo tee -a /etc/dnsmasq.conf > /dev/null
  - echo "address=/local/127.0.0.1" | sudo tee -a /etc/dnsmasq.conf > /dev/null
  - echo "user=root" | sudo tee -a /etc/dnsmasq.conf > /dev/null
  - sudo service dnsmasq restart

  # add proper c++- compiler for node-sass
  - sudo apt-get install gcc-4.8 g++-4.8
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 20
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 20
  - sudo g++ --version
  - npm config set python /usr/bin/python2.7

before_script:
  - psql -c 'create database keybar_test;' -U postgres

script:
  - psql --version
  - make develop
  - make test

after_success:
  - pip install "coveralls==0.4.1" coverage
  - coverage report
  - coveralls
